### PR TITLE
Update user_palette.js

### PR DESCRIPTION
**Pull request by anurajbhandari5**
## Fixes issue

Closes: #issue_number

Addresses: #issue_number (if multiple persons are assigned, the issue)

## Proposed changes

Brief description of what is fixed or changed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rajats98** [comment]
@anurajbhandari5 Resolve the merge conflict, In case you need any help, kindly ask!

**Comment by rajats98** [comment]
@anurajbhandari5 there is a bracket mismatch please check, and also delete the empty lines added

**Comment by anurajbhandari5** [comment]
okay

**Comment by rajats98** [comment]
Excellent Work!

**Pull request merged**
