### PR TITLE
Landing Page Design

### LINKED ISSUE #4: Create Web design(UI design)
### Create UI design in any _designing_ software (no restrictions on software, can be online/offline)

We need 1-3 pages i.e.

- [x] **Landing/Cover Page**
          Depends on your creativity, you can add a description, animation, or anything you feel 
          relevant

- [x] **Input form**
          This form contains only one required input field, that takes an image of leaf as input.
          
- [x] **Result**
         Here the result presented under 3 categories, namely,  Symptoms, Treatment, and 
         Recommended products.

1. One can work on one or more than one the these.
2. Cover page is optional.
3. Whole thing/flow can be shown on one or more pages.

**Add all the pictures/animations/icons or their link with your PR.** 
Submit in a proper format, so that UI developers can use it without having the designing tool.

This task is open to the creativity of the contributor.

Refer these: 
https://medium.theuxblog.com/11-best-prototyping-tools-for-ui-ux-designers-how-to-choose-the-right-one-c5dc69720c47
https://www.creativebloq.com/how-to/20-best-ui-design-tools

### PR DESCRIPTION
**Pull request by Adyasha8105**
Added new Landing page design #9 
I made this design using adobe xd and Illustrator.
This PR addresses #4

### CODE REVIEW

**Review by rajats98 — CHANGES_REQUESTED** [review]
**Great work!!**
Just a few changes, 
1. submit your files in Web Designs/design-2
1. remove the signup button 
1. Change text of **Know More** button to Analyse/Start Analysing, or Add a new button- Analyse (whichever suits you)
1. Also, add the picture(s)/animation component as png in resources folder(create it inside design-2), Otherwise the developer might need to first download and install Adobe XD.

your design is really good !!

**Comment by Adyasha8105** [comment]
@rajats98 Can you check my PR?
If you don't mind, please consider this task to be medium to hard level as I have used Adobe xd and illustrator.

**Comment by rajats98** [comment]
Add the picture(s)/animation component(i.e image of farmers, image on left side of result page) as png in resources folder(create it inside design-2).
Yeah don't worry about points/labels, I know it takes time to make a design :smiley: 

Hint: You can select and export the components of your design using the software you are using to design(XD/illustrator)

**Comment by Adyasha8105** [comment]
@rajats98 Done 👍

**Comment by Adyasha8105** [comment]
@rajats98 Now you can check my PR?

**Comment by Adyasha8105** [comment]
> Add the picture(s)/animation component(i.e image of farmers, image on left side of result page) as png in resources folder(create it inside design-2).
> Yeah don't worry about points/labels, I know it takes time to make a design 😃
> 
> Hint: You can select and export the components of your design using the software you are using to design(XD/illustrator)

Yup 💯 .

**Review by rajats98 — APPROVED** [review]

**Pull request merged**
