### PR TITLE
 Logo Design no.2

### PR DESCRIPTION
**Pull request by Adyasha8105**
This PR solves issue #1.
  
The logo is explained as follows:
It just gives a connection between science and agriculture (farming).
As the main role of science in agriculture has been to help us generate novelties that allow us to produce more with less land and less effort. It resembles the scientific curiosity to help save plants.

### CODE REVIEW

**Comment by Adyasha8105** [comment]
@rajats98 Sir, can you check my PR?

**Review by rajats98 — CHANGES_REQUESTED** [review]
Try resizing the image to 500 by 500 pixels. (you can pad it some empty space, and rest is upon your creativity) and add it with the same name appended with (500x500 px)
And also **Let this logo file as it is.**

So update PR will have 2 files **this file and the updated file.**

**Comment by Adyasha8105** [comment]
@rajats98 can I do force push?
actually my new image is in 531*137 px. will it be ok?

**Comment by rajats98** [comment]
Why do you want to force push? if there is any issue we can discuss, I don't think force push is required.

**Comment by Adyasha8105** [comment]
> Why do you want to force push? if there is any issue we can discuss, I don't think force push is required.

ya sorry.
What about the image ( w*h)?

**Comment by rajats98** [comment]
It's okay you need not be.
Although there are no changes in repo, I guess...so force push should not be an issue.
But I just want to learn why do you wanted force push?

**Comment by Adyasha8105** [comment]
Actually I am new to GitHub so maybe that was not the word I am looking for.
So sorry.

**Comment by Adyasha8105** [comment]
@rajats98 what about the image pixel?
actually my new image is in 531*137 px. will it be ok?

**Comment by rajats98** [comment]
Hey, 
I missed the edited part... try making it 500x500pixel, add some white space(above and below it) and crop 531px to 500px.
Actually, otherwise, it can't be updated as github profile pic(for the project)

**Comment by Adyasha8105** [comment]
> Hey,
> I missed the edited part... try making it 500x500pixel, add some white space(above and below it) and crop 531px to 500px.
> Actually, otherwise, it can't be updated as github profile pic(for the project)

Done 👍 .
Is it Ok now?

**Review by rajats98 — APPROVED** [review]

**Comment by rajats98** [comment]
Hey @Adyasha8105, 
I just noticed your logo contains white-background, it will be great if you can update both of your designs with a transparent background. 
Make another PR, you will be getting points (corresponding to easy tag)

**Pull request merged**
