### PR TITLE
Add logo design no.5

### PR DESCRIPTION
**Pull request by Kashish-max**
addresses #1

### CODE REVIEW

**Review by rajats98 — CHANGES_REQUESTED** [review]
Hey
Pull the latest code and submit your logo-design in designs/logo-designs/submitted-logos
logodesign-3.png from root location, just add it only once at the above-mentioned location.

**Comment by Kashish-max** [comment]
Sorry, I added this twice by some internet problem

**Comment by rajats98** [comment]
> Sorry, I added this twice by some internet problem

It's okay @kashish-max 
just make the corrections and update

**Comment by rajats98** [comment]
@Kashish-max Kindly Update, now you need to update the file name too, choose the next number.

**Pull request merged**
