### PR TITLE
Landing Page-3 Rectified

### PR DESCRIPTION
**Pull request by goyalmuskan**
Screenshot (82)

### CODE REVIEW

**Review by rajats98 — CHANGES_REQUESTED** [review]
1. I would suggest you to remove any scrolling, but if you want the user to feel effect of the navbar transition on scrolling, make sure whole background have a color (I can see some white space on scrolling up)


1. For small/mobile size I would suggest you to remove the tree(optional), it's your call
1. There is some unwanted scroll on small screen size (horizontal scroll), make it stable.. (tip: you can use overflow:hidden for #main_section)

1. Add logo

1. you may also remove the lens for medium screen size (it will give some spacing)

Great Work!!

**Comment by goyalmuskan** [comment]
> 1. I would suggest you to remove any scrolling, but if you want the user to feel effect of the navbar transition on scrolling, make sure whole background have a color (I can see some white space on scrolling up)
> 2. For small/mobile size I would suggest you to remove the tree(optional), it's your call
> 3. There is some unwanted scroll on small screen size (horizontal scroll), make it stable.. (tip: you can use overflow:hidden for #main_section)
> 4. Add logo
> 5. you may also remove the lens for medium screen size (it will give some spacing)
> 
> Great Work!!

Thank you Sir, also, which logo should I use? @rajats98

**Comment by rajats98** [comment]
> Thank you Sir, also, which logo should I use? @rajats98

designs/logo-designs/cropAi-logo-croped.png or designs/logo-designs/cropAi-logo.png

**Comment by goyalmuskan** [comment]
Done! @rajats98

**Comment by abhushanaj** [comment]
@rajats98  Sir isn't  this repetitive with https://github.com/CropAi/Frontend/pull/16

**Comment by rajats98** [comment]
> @rajats98 Sir isn't this repetitive with #16

Thanks for attracting my attention to possible anomaly but **that was design(images) and this is code :P**

**Comment by abhushanaj** [comment]
> > @rajats98 Sir isn't this repetitive with #16
> 
> Thanks for attracting my attention to possible anomaly but **that was design(images) and this is code :P**

Dang! they look identical! Awesome work @goyalmuskan !

**Pull request merged**
