### PR TITLE
contributor-page added with mobile and web design with their resource…

### PR DESCRIPTION
**Pull request by Satyam3976**
…s file

## Fixes issue

Closes: #issue_number

Addresses: #57 

## Proposed changes

Brief description of what is fixed or changed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Satyam3976** [comment]
contributor-page-web
contributor-page-mobile

**Review by rajats98 — COMMENTED** [review]
Awesome work!!
Really creative work.

It would be great, if you can also give a unisex styled dummy, (we may or may not get the genders)

**Comment by Satyam3976** [comment]
Thank you so much sir
Changes are done, but I haven't removed the female dummy png from the folder so that in future if someone needs, he/she can use it

**Comment by rajats98** [comment]
great !!

**Comment by rajats98** [comment]
> Thank you so much sir
> Changes are done, but I haven't removed the female dummy png from the folder so that in future if someone needs, he/she can use it

btw I was asking for a new image (which can represent both genders), but not an issue we can use the male-one for females too :+1:

**Pull request merged**
