### PR TITLE
Folders restructure

### LINKED ISSUE #18: Create required directories
1. Create folders as per this folder structure
  ```
  ../src
      ../assets
      ../img
      ../lib	
      ../landing pages
             ../landing page 2
             ../landing page 3
  ```

2. Rename style.css and script.js to index.js and index.css and move both files to assets.
And update index.html accordingly.

### PR DESCRIPTION
**Pull request by abhushanaj**
fixes #18

### CODE REVIEW

**Comment by rajats98** [comment]
Hey @abhu-A-J, you also need to create folders(empty) as given in #18 point 1.

**Review by rajats98 — CHANGES_REQUESTED** [review]
Add empty folders as in #18 (point1)

**Comment by abhushanaj** [comment]
> Add empty folders as in #18 (point1)

@rajats98  I think it's not pushing empty folders beacuse I created them and they exist on my machine! Should I add some temp file inside it ??

**Comment by rajats98** [comment]
> > Add empty folders as in #18 (point1)
> 
> @rajats98 I think it's not pushing empty folders beacuse I created them and they exist on my machine! Should I add them temp file inside it ?

yes
in landing page 2 and 3, add empty landing2.html and landing3.html
and in others add temp files

**Comment by abhushanaj** [comment]
> > > Add empty folders as in #18 (point1)
> > 
> > 
> > @rajats98 I think it's not pushing empty folders beacuse I created them and they exist on my machine! Should I add them temp file inside it ?
> 
> yes
> in landing page 2 and 3, add empty landing2.html and landing3.html
> and in others add temp files

I think it's okay now Sir, sorry I directly pushed from the master. Totally forgot to make a new branch fo this.

**Review by rajats98 — APPROVED** [review]

**Comment by rajats98** [comment]
> I think it's okay now Sir, sorry I directly pushed from the master. Totally forgot to make a new branch fo this.

It's okay, no problem

**Pull request merged**
