### PR TITLE
Displaying the image entered on form

### LINKED ISSUE #79: Show input image
inside input_container
		show input image on the form( at place of dummy image icon)

**At one time only one of the div will be shown (landing_container/ input_container/ result_container).**

### PR DESCRIPTION
**Pull request by abhushanaj**
## Fixes issue

Closes: #79 

## Proposed changes

Added event handlers to show entered input by user through the form

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

## Screenshots (if appropriate)
Screenshot (84)

### CODE REVIEW

**Comment by rajats98** [comment]
great,
but when a picture of bit larger than this is added, some scrolling occurs,can you update the css/design, so that page remains stable. if the image is very large then it's okay(otherwise you can give set some max-width and max-height ).
Do this also will upgrade the PR to Medium.

**Comment by abhushanaj** [comment]
> great,
> but when a picture of bit larger than this is added, some scrolling occurs,can you update the css/design, so that page remains stable. if the image is very large then it's okay(otherwise you can give set some max-width and max-height ).
> Do this also will convert it to Medium.

Okay Sir,  I will do the same. Can you give some estimate on bigger size images, so I can think accordingly! (rough size will do)

**Comment by rajats98** [comment]
> Okay Sir, I will do the same. Can you give some estimate on bigger size images, so I can think accordingly! (rough size will do)

Since we can't control user input, expect max size to be 1000x1000px, you may check how much can you afford maximum, and show any image larger than that in only that much size (image can be resized/cropped for larger image)

**Comment by abhushanaj** [comment]
> > Okay Sir, I will do the same. Can you give some estimate on bigger size images, so I can think accordingly! (rough size will do)
> 
> Since we can't control user input, expect max size to be 1000x1000px, you may check how much can you afford maximum, and show any image larger than that in only that much size (image can be resized/cropped for larger image)

Done!!! I think now it will work on portrait images as well which has longer height than width!!! 
No scrolling is present as usual. Can you test again with the same image you used to test last time and even some more to be sure! I didn't change previously written styles , just  little bit to get more space!

**Comment by abhushanaj** [comment]
> great,
> but when a picture of bit larger than this is added, some scrolling occurs,can you update the css/design, so that page remains stable. if the image is very large then it's okay(otherwise you can give set some max-width and max-height ).
> Do this also will convert it to Medium.

Sir you forgot to add the label here!!! Thanks! 😅😋

**Pull request merged**
