### PR TITLE
Result design

### LINKED ISSUE #103: Make our website responsive
index.html
Update bootstrap to the latest version (4.4.1)
update bootstrap to latest version and update pages according to that, no scrolling on any page (expect result page, when content is large, only vertical scroll), no horizontal scroll in any case

Use bootstrap extensively to design, position(spacing and size, etc.) elements

colors/design may be changed, it must look aesthetic.
remove/update the redundant CSS on the go.
**Make the design responsive**

Before starting with it, understand what each and every element does.
Understand the flow of the whole code and website.
No functionality should be changed, no functionality should be broken.

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

This issue will be assigned to @abhu-A-J, considering the previous contributions and understanding of the code.

### PR DESCRIPTION
**Pull request by abhushanaj**
closes #103 
Addresses #103 Part 3: Result Page

*Merge in order*

- Fixed issues for hiding content on smaller w/h ratio devices
- scrolling introduced on result page
- scrolling not present on another page
- responsive
- new design on the layout of the result page
- mirror effect on containers
- subtle changes on shadows and text
- made design consistent with other pages

**IMP**
- Styles from temp.css has been shifted to index.css 
- Card.css has been removed (not needed anymore)
- Index.html has been cleaned out reference of temp stylesheet

**PREVIEW**
The content might be blurred out in screenshots
Screenshot (117)

### CODE REVIEW

**Comment by abhushanaj** [comment]
@rajats98 Sir, you can cross-check to verify if everything is okay! If not let me know and I'll try to correct them!

**Comment by rajats98** [comment]
give some background to result, it's a bit difficult to read over the grass, otherwise, It looks great

**Comment by abhushanaj** [comment]
> give some background to result, it's a bit difficult to read over the grass, otherwise, It looks great

Sir, should I give an image or a gradient??

**Comment by rajats98** [comment]
Your choice, but it should be easily readable... You can give a plain color also

**Comment by abhushanaj** [comment]
> Your choice, but it should be easily readable... You may give a plain color also

Done Sir, it's very light but it is enough to contrast out text with background! It not visible on screenshot correctly!

**Comment by rajats98** [comment]
Awesome!

**Pull request merged**
