### PR TITLE
Add color palette

### PR DESCRIPTION
**Pull request by Geesa-Vihara**
Address #170 
Please don't merge this, I want to resolve a merge conflict

palette

### CODE REVIEW

**Comment by rajats98** [comment]
Hello @Geesa-Vihara , Welcome to this project!!
I want to know, if you are a GSSoC'20 participant, as this project is only for them.
If yes, Great!
even if you are not, you can still make contributions to open for all issues(only), I would love to review your pull request for that!

**Comment by Geesa-Vihara** [comment]
> 
> 
> Hello @Geesa-Vihara , Welcome to this project!!
> I want to know, if you are a GSSoC'20 participant, as this project is only for them.
> If yes, Great!
> even if you are not, you can still make contributions to open for all issues(only), I would love to review your pull request for that!

Hi @rajats98 Yes I am a GSSoc'20 participant

**Comment by rajats98** [comment]
Awesome! Welcome to CropAi once again!!

**Comment by rajats98** [comment]
@Geesa-Vihara, Now there is merge conflict, resolve it! if you any doubt or issue, you can ask!

**Comment by Geesa-Vihara** [comment]
> 
> 
> @Geesa-Vihara, Now there is merge conflict, resolve it! if you any doubt or issue, you can ask!

@rajats98 Can you check whether I have done it properly?

**Comment by rajats98** [comment]
> @rajats98 Can you check whether I have done it properly?

Perfect :100: !

**Pull request merged**
