### PR TITLE
Contribution-page added

### PR DESCRIPTION
**Pull request by Adyasha8105**
## Fixes issue
Addresses: #57 

## Proposed changes

Added a design for the contribution page

## Description

- I have added a design for the contribution page using various designing tools i.e Adobe xd and Illustrator. 
- I have used a lot many tools, so I think it can be considered as a hard level task.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

## Screenshots (if appropriate)
(Attached)

### CODE REVIEW

**Review by rajats98 — COMMENTED** [review]
Awesome!!
Can you add attach a dummy photo, in case someone's pic is not available.
Provide a unisex dummy, so that it can be added to male and female both.
Just attach its png separately no need to modify your design

**Comment by Adyasha8105** [comment]
> Awesome!!
> Can you add attach a dummy photo, in case someone's pic is not available.
> Provide a unisex dummy, so that it can be added to male and female both.
> Just attach its png separately no need to modify your design

Ok then :)

**Comment by Adyasha8105** [comment]
I have added the dummy picture and made a little change in the page ( i.e at the header part, I have made a box using the effect of shadow).
Can this task be considered as Hard level as I have used a lot my designing tools?
Hopefully, You may like my Design 👍 .

**Comment by rajats98** [comment]
> I have added the dummy picture and made a little change in the page ( i.e at the header part, I have made a box using the effect of shadow).

:100: 

> Can this task be considered as Hard level as I have used a lot my designing tools?

Unfortunately No, it will be considered as medium. I apperciate your hard work, and the toolset you used, but since it is a single page design, we would stick to medium.

> Hopefully, You may like my Design  .

yes for sure, your design is Awesome

btw In the last review, I meant a common image, that we can use if picture of a person is not available (regardless of its gender, we might not have genders of contributor ), like the one WhatsApp uses for empty profile pic.
but, It is okay, Merging this PR, No worry

**Comment by Adyasha8105** [comment]
> > I have added the dummy picture and made a little change in the page ( i.e at the header part, I have made a box using the effect of shadow).
> 
> 💯
> 
> > Can this task be considered as Hard level as I have used a lot my designing tools?
> 
> Unfortunately No, it will be considered as medium. I apperciate your hard work, and the toolset you used, but since it is a single page design, we would stick to medium.
> 
> > Hopefully, You may like my Design  .
> 
> yes for sure, your design is Awesome
> 
> btw In the last review, I meant a common image, that we can use if picture of a person is not available (regardless of its gender, we might not have genders of contributor ), like the one WhatsApp uses for empty profile pic.
> but, It is okay, Merging this PR, No worry

Okay, it's fine sir 👍 .

**Pull request merged**
