### PR TITLE
Fixed #52 (About button functionality )

### LINKED ISSUE #52: About button functionality
**index.html**
On clicking about show brief of project/application on right side (or wherever you like, but be sane :p), it should look good and the user must get a good experience,
**Do not remove the button while showing this, size or position may be changed (but avoid change of position/size)**  

You may show this _"CorpAi is a crop advisory app for farmers and gardeners. It can diagnose pest damage, plant disease and nutrient deficiencies that are affecting crops and can offer corresponding treatment measures."_

Any modification should be done inside **div with id=landing_container**

### PR DESCRIPTION
**Pull request by annu12340**
## Fixes issue

Closes: #52  

## Proposed changes

Added a toggle feature in the button

## Description

Using jquery,  I have added the hide/show feature on the btn

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by rajats98 — CHANGES_REQUESTED** [review]
Your design is very good, but you need to make the following changes

change id to about_content (from target)
change id to about_btn (from toggle)

move the content after the analyze button ( content below both buttons, both button remains still),in my opinion it will improve user experience.

jquery already added(remove that you added, and you may add a comment above the one already added)

remove .Hide class it is already there (.hidden)

while working on open source,
 you should try naming things meaningfully, so that code is easily legible and  they communicate intent
also you must read the current code, so that no redundancy occurs in code.

**Comment by rajats98** [comment]
you may make some changes to landing_container div's css, if currently it is making your job difficult : )

**Comment by rajats98** [comment]
great!!

**Comment by annu12340** [comment]
:)

**Pull request merged**
