### PR TITLE
Replacement of greetings actions

### PR DESCRIPTION
**Pull request by abhushanaj**
Correction of getting actions for first-time contributors!
@rajats98 Sir, It is working now! Builds have passed!

### CODE REVIEW

**Comment by rajats98** [comment]
check this:
https://github.com/CropAi/Frontend/blob/aeb4a7d3627b289b252403f28152ced53f23c207/.github/workflows/greetings.yml
(initial version, almost the same as yours, it was not working too)

**Comment by abhushanaj** [comment]
> check this:
> https://github.com/CropAi/Frontend/blob/aeb4a7d3627b289b252403f28152ced53f23c207/.github/workflows/greetings.yml
> (initial version, almost the same as yours, it was not working too)

It work's its the one I used in backend repo and it's passing every time and showing correct messages on first-timers.
These greeting message don't work for people who have already contributed.

Although they might fail once or twice if builds takes longer time

**Comment by rajats98** [comment]
> > check this:
> > https://github.com/CropAi/Frontend/blob/aeb4a7d3627b289b252403f28152ced53f23c207/.github/workflows/greetings.yml
> > (initial version, almost the same as yours, it was not working too)
> 
> It work's its the one I used in backend repo and it's passing every time and showing correct messages on first-timers.
> These greeting message don't work for people who have already contributed.
> 
> Although they might fail once or twice if builds takes longer time

Maybe they only failed once or twice for new users! Let's try again

**Comment by abhushanaj** [comment]
> > > check this:
> > > https://github.com/CropAi/Frontend/blob/aeb4a7d3627b289b252403f28152ced53f23c207/.github/workflows/greetings.yml
> > > (initial version, almost the same as yours, it was not working too)
> > 
> > 
> > It work's its the one I used in backend repo and it's passing every time and showing correct messages on first-timers.
> > These greeting message don't work for people who have already contributed.
> > Although they might fail once or twice if builds takes longer time
> 
> Maybe they only failed once or twice for new users! Let's try again

Yes, they might fail in some cases! not perfect

**Pull request merged**
