### PR TITLE
two new logos added

### PR DESCRIPTION
**Pull request by Aakansha99**
logos describing the research information related to agriculture will be supplied in the application

## Fixes issue

Closes: #issue_number

Addresses: #issue_number (if multiple persons are assigned, the issue)

## Proposed changes

Brief description of what is fixed or changed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe):

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by rajats98 — CHANGES_REQUESTED** [review]
Kindly change the names of your file to next avail names, i.e **logodesign-8 and logodesign-9**


PicsArt_04-03-01.34.46.jpg have white background(not transparent), if possible, update it with a transparent background(optional).

Designs are really **Very creative and meaningful!!**

**Comment by Aakansha99** [comment]
I will make the changes by tomorrow. Thank you for your reviews

**Comment by rajats98** [comment]
Hey,
Great work!! But can you change name of logodesign-7 to 9, We got another entry for logodesign-7.

**Comment by Aakansha99** [comment]
I have changed the name of logodesign from 7 to 9

**Pull request merged**
