### PR TITLE
Contribution page

### PR DESCRIPTION
**Pull request by abhushanaj**
addresses #57 
contribution page

### CODE REVIEW

**Review by rajats98 — CHANGES_REQUESTED** [review]
Nice design,
Add a generic image, if image of someone is not available (We might not require it but still, good practice) 
show design of atleast one hovered item

And I hope the design image spread over more than one page (i.e it is designed for landscape screen).

**Comment by rajats98** [comment]
addresses #57

**Comment by abhushanaj** [comment]
Okay, got it. I'll do something like mentors and admins on first page and participant in second page. 

Also when you mean generic images , does it mean the same image on all of them, or more like a demo pic(not really a human picture) but more like a illustration kind on all of them. 

Okay I'll make the addition of hover effect as well.

**Comment by rajats98** [comment]
> Okay, got it. I'll do something like mentors and admins on first page and participant in second page.
> 

Hey no, don't 
Actually, your image has more height than width, so I was just confirming that you designed it for landscape screen.

> Also when you mean generic images , does it mean the same image on all of them, or more like a demo pic(not really a human picture) but more like a illustration kind on all of them.
> 
Yup the illustration thing, like you see in facebook/whatsapp profile without a DP

> Okay I'll make the addition of hover effect as well.
yup

**Comment by abhushanaj** [comment]
> > Okay, got it. I'll do something like mentors and admins on first page and participant in second page.
> 
> Hey no, don't
> Actually, your image has more height than width, so I was just confirming that you designed it for landscape screen.
> 
> > Also when you mean generic images , does it mean the same image on all of them, or more like a demo pic(not really a human picture) but more like a illustration kind on all of them.
> 
> Yup the illustration thing, like you see in facebook/whatsapp profile without a DP
> 
> > Okay I'll make the addition of hover effect as well.
> > yup

Oh yeah it has no height than width, but dimensions on design are not really to be replicated, they are just for reference on how the layout to move. It's meant for landscape view only . The design is to tell how where to place items , and while you develop it, you can change the dimensions as per need, that's why I didn't link to figma on this one! So only thing I need to change is images right?

**Comment by rajats98** [comment]
Yup great!

**Comment by rajats98** [comment]
> Yup great!

You need to update image and hover effect

**Comment by abhushanaj** [comment]
Sir can you add labels here!!?? 👍

**Comment by rajats98** [comment]
Yes I can :sunglasses:

**Pull request merged**
