### PR TITLE
Button alignments

### PR DESCRIPTION
**Pull request by darkmatter18**
## Fixes issue

Closes: #273 

Addresses: #273 (if multiple persons are assigned, the issue)

## Proposed changes

- Analyze other Crop button re alligned
- Home Buttons are alligned for mobile displays

## Description

- Analyze other Crop button re alligned
- Home Buttons are alligned for mobile displays

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

## Screenshots (if appropriate)
Annotation 2020-04-27 200024
Annotation 2020-04-27 200416

### CODE REVIEW

**Comment by rajats98** [comment]
Recheck for 400-700px screen width!, there are issues!

**Comment by rajats98** [comment]
@darkmatter18 add some space b/w button, screen-width: 400-500px!

**Comment by darkmatter18** [comment]
@rajats98 I tried to solved that part. But seems like the Bootstrap have some issue on that region. I also checked that mobile and tablet devices are usually don't fall on that region and works well. But still if you tell me to do that, then I have to impliment some custom CSS with some media quary. Shall I do that?

**Comment by rajats98** [comment]
@darkmatter18 check slack!

**Comment by darkmatter18** [comment]
@rajats98 Kindly check

**Review by rajats98 — APPROVED** [review]
Great work!
upgrading it to medium, since it took more efforts than I thought

**Pull request merged**
